### PR TITLE
Add Test Playground

### PR DESCRIPTION
**Pull request by matthew16550**
(PR moved from plantuml/plantuml#485 - with slightly updated code.  Also added [AssertJ](https://joel-costigliola.github.io/assertj/) which I hope is agreeable, it's comprehensive & I find it fun to use!)

I've been experimenting with this idea while refactoring `ImageParameter`, it's been helpful to batch render various diagrams with different settings then compare in a grid.  Thought I'd suggest it here to see if other devs would make use of it.

As an example, below is the current situation for `scale` & `dpi` support.  The first row uses neither, the second row has `scale 2` and the last row has `skinparam dpi 192`.  We already know these are not consistently implemented, the picture makes the details clearer and re-rendering it will give quick feedback as I adjust that code.

sizing

It was created by:
```java
ALL_ALLOWING_SKINPARAM

  // Make PNGs in the "no_style" dir
  .render(PNG, "no_style")
  
  // Make PNGs in the "scale_2" dir using "scale 2"
  .render(PNG, "scale_2", "scale 2")
  
  // Make PNGs in the "dpi_192" dir using "skinparam dpi 192"
  .render(PNG, "dpi_192", "skinparam dpi 192")
  
  // Make "sizing.png" (the image above) comparing PNGs from "no_style", "scale_2" & "dpi_192" dirs
  .pngHorizontal("sizing", "no_style", "scale_2", "dpi_192");
```

My earlier attempt tried to specify the same sort of thing in a JSON file but I quickly found it was not flexible so changed to this idea which is just some Java methods that can be joined together in various ways.

The target users here are other PlantUML developers so I haven't thought about making it end-user friendly with CLI support etc.

### CODE REVIEW

**Comment by arnaudroques** [comment]
Great work!
However, I cannot merge the PR because the CI is failing.

**Comment by matthew16550** [comment]
Looks like a permission problem downloading the snapshot jar.  Not sure if I will have any time in the next few days but will be back at it when I can.

**Comment by matthew16550** [comment]
@arnaudroques The build is passing.  Maven snapshots I think are not the simplest way for now, see `README.md` & the comment in `ci.yml`.  If this approach is agreeable I will tidy up plantuml/plantuml#485 so the couple of changes that are still needed there can be merged before this one.

**Comment by matthew16550** [comment]
@arnaudroques all ready here I think.

**Pull request merged**
